# Generated by Django 4.2.6 on 2024-03-28 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0004_remove_create_job_question_id_create_job_id'),
        ('employee', '0002_remove_employee_phone_employee_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormFill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formfilling_date', models.DateField(auto_now=True)),
                ('expected_delivery', models.IntegerField(default=0)),
                ('est_budget', models.IntegerField(blank=True, default=0)),
                ('resume', models.FileField(upload_to='static/resume/')),
                ('status', models.CharField(default='pending', max_length=30)),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
                ('employer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employer.employer')),
            ],
        ),
    ]
