# Generated by Django 4.2.6 on 2024-03-29 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0004_remove_create_job_question_id_create_job_id'),
        ('employee', '0004_formfill_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formfill',
            name='employer_id',
        ),
        migrations.AddField(
            model_name='formfill',
            name='job_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='employer.create_job'),
            preserve_default=False,
        ),
    ]
