# Generated by Django 4.2.6 on 2024-03-29 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_alter_formfill_employee_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formfill',
            name='employee_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee'),
        ),
    ]
