# Generated by Django 4.2.6 on 2024-03-28 19:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employer', '0002_employer_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='create_job',
            fields=[
                ('question_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('job_description', models.CharField(default='no description', max_length=5000)),
                ('job_domain', models.CharField(default='not provided', max_length=50)),
                ('upload_date', models.DateField(auto_now=True)),
                ('due_date', models.DateField(blank=True)),
                ('est_budget', models.IntegerField(blank=True)),
                ('status', models.CharField(default='live', max_length=30)),
                ('employer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
