# Generated by Django 4.2.6 on 2024-03-28 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0003_create_job'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='create_job',
            name='question_id',
        ),
        migrations.AddField(
            model_name='create_job',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
