# Generated by Django 4.2.6 on 2024-03-29 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0004_remove_create_job_question_id_create_job_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='create_job',
            name='job_heading',
            field=models.CharField(default='na', max_length=500),
        ),
        migrations.AlterField(
            model_name='create_job',
            name='employer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employer.employer'),
        ),
    ]
